#!/usr/bin/env node
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { join, resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { parse } from "csv-parse/sync";

const SCHEMA_PREFIX_RE = /^https?:\/\/schema\.org\//i;
const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(__dirname, "..");

const releaseDir =
  process.argv[2] ??
  process.env.SCHEMAORG_RELEASE_DIR ??
  "C:\\Users\\zippy\\source\\repos\\schemaorg\\schemaorg\\data\\releases\\30.0";
const versionsPath =
  process.env.SCHEMAORG_VERSIONS_JSON ??
  "C:\\Users\\zippy\\source\\repos\\schemaorg\\schemaorg\\versions.json";

if (!existsSync(releaseDir)) {
  console.error(`Schema.org release directory not found: ${releaseDir}`);
  process.exit(1);
}

const typesPath = join(releaseDir, "schemaorg-all-https-types.csv");
const propertiesPath = join(releaseDir, "schemaorg-all-https-properties.csv");

if (!existsSync(typesPath) || !existsSync(propertiesPath)) {
  console.error(`Expected CSVs not found in: ${releaseDir}`);
  process.exit(1);
}

const version = existsSync(versionsPath)
  ? (JSON.parse(readFileSync(versionsPath, "utf8")).schemaversion ?? "unknown")
  : "unknown";

function strip(id) {
  return id.replace(SCHEMA_PREFIX_RE, "");
}

function splitList(field) {
  if (field === undefined || field === null || field === "") return [];
  return field
    .split(",")
    .map((s) => strip(s.trim()))
    .filter((s) => s.length > 0);
}

const typeRows = parse(readFileSync(typesPath, "utf8"), { columns: true, skip_empty_lines: true });
const propertyRows = parse(readFileSync(propertiesPath, "utf8"), {
  columns: true,
  skip_empty_lines: true,
});

const types = {};
for (const row of typeRows) {
  const name = strip(row.id);
  types[name] = { subTypeOf: splitList(row.subTypeOf) };
}

const properties = {};
for (const row of propertyRows) {
  const name = strip(row.id);
  properties[name] = {
    domainIncludes: splitList(row.domainIncludes),
    rangeIncludes: splitList(row.rangeIncludes),
  };
}

const sortedTypes = Object.keys(types)
  .sort()
  .reduce((acc, k) => {
    acc[k] = types[k];
    return acc;
  }, {});
const sortedProps = Object.keys(properties)
  .sort()
  .reduce((acc, k) => {
    acc[k] = properties[k];
    return acc;
  }, {});

const out = `// AUTO-GENERATED by scripts/build-vocab.mjs from Schema.org release ${version}.
// Do not edit by hand — run \`npm run build:vocab\` to regenerate.
/* eslint-disable */

export const VOCAB_VERSION = ${JSON.stringify(version)};

export interface VocabType {
  subTypeOf: string[];
}

export interface VocabProperty {
  domainIncludes: string[];
  rangeIncludes: string[];
}

export const types: Record<string, VocabType> = ${JSON.stringify(sortedTypes)};

export const properties: Record<string, VocabProperty> = ${JSON.stringify(sortedProps)};
`;

const target = join(REPO_ROOT, "src", "validate", "vocab.generated.ts");
writeFileSync(target, out, "utf8");

const typeCount = Object.keys(sortedTypes).length;
const propCount = Object.keys(sortedProps).length;
console.log(`Wrote ${target} (Schema.org ${version}, ${typeCount} types, ${propCount} properties)`);
